[Canary test] Vectorized_map
As we are discussed in https://github.com/keras-team/keras-cv/pull/143#issuecomment-1047215737 this is going to fail (check the CI) cause:
```
ValueError: Input "maxval" of op 'RandomUniformInt' expected to be loop invariant.
```

As I've mentioned in the thread we really need to understand if we want to have randomness inside the batch or between the batches and what kind of impact we have between the computing overhead, contributing speed/code readability  and  network convergence.

Also I don't know if @joker-eph  or @qlzh727 could expose use a little bit the pro and cons of `jit_comile` a function vs using the `vectorized_map` or if they are orthogonal. With many CV transformations  we cannot compile the function as the underline `tf.raw_ops.ImageProjectiveTransformV3 ` op isn't supported by XLA.